import os
import torch
import pytorch_lightning as pl
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from train_meta_lit import BakeryMetaClassifier

# --- 1. Dataset for Prediction ---
class PredictionDataset(Dataset):
    def __init__(self, support_dir, query_image_path, k_shot):
        self.support_dir = support_dir
        self.query_image_path = query_image_path
        self.k_shot = k_shot
        
        self.transform = transforms.Compose([
            transforms.Resize((84, 84)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
        self.class_names = sorted([d for d in os.listdir(support_dir) 
                                   if os.path.isdir(os.path.join(support_dir, d))])

    def __len__(self):
        return 1 # Single inference task

    def __getitem__(self, idx):
        support_imgs = []
        support_lbls = []
        
        # Build Support Set
        for c_idx, c_name in enumerate(self.class_names):
            c_dir = os.path.join(self.support_dir, c_name)
            imgs = os.listdir(c_dir)[:self.k_shot]
            
            for img_name in imgs:
                img = Image.open(os.path.join(c_dir, img_name)).convert('RGB')
                support_imgs.append(self.transform(img))
                support_lbls.append(c_idx)
                
        # Load Query Image
        query_img = Image.open(self.query_image_path).convert('RGB')
        query_img = self.transform(query_img).unsqueeze(0) # [1, C, H, W]
        
        return torch.stack(support_imgs), torch.tensor(support_lbls), query_img

if __name__ == '__main__':
    # Update this with the actual file generated by Script 1
    CHECKPOINT = "./resources/checkpoints/protonet-epoch=09-train_loss=0.15.ckpt" 
    SUPPORT_DIR = "./datasets/meta_learning/eval" 
    QUERY_IMAGE = "./datasets/meta_learning/eval/class_A/sample_test.jpg"

    # 1. Load Model with stored hyperparams
    model = BakeryMetaClassifier.load_from_checkpoint(CHECKPOINT)
    
    # 2. Prepare Data (batch_size=1 means model gets 1 full evaluation episode)
    dataset = PredictionDataset(SUPPORT_DIR, QUERY_IMAGE, k_shot=5)
    dataloader = DataLoader(dataset, batch_size=1)
    
    # 3. Distributed/Batched Prediction using LitAPI
    trainer = pl.Trainer(accelerator='auto')
    predictions = trainer.predict(model, dataloaders=dataloader)
    
    # predict() returns a list containing outputs from predict_step (one per batch)
    pred_idx = predictions[0][0].item()
    
    print(f"Predicted Class: {dataset.class_names[pred_idx]}")
