import torch
import torchvision.transforms as transforms
from PIL import Image
# Import the class definition from the training script
from training.meta_learning.torch_base import ProtoNet 

def predict_single_image(checkpoint_path: str, support_dir: str, query_image_path: str):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # 1. Load Model
    model = ProtoNet.load_from_checkpoint(checkpoint_path)
    model.to(device)
    model.eval()
    
    # Standard transforms
    transform = transforms.Compose([
        transforms.Resize((84, 84)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    # 2. Build Support Set (N-way, K-shot from evaluation directory)
    import os
    support_images = []
    support_labels = []
    class_names = sorted(os.listdir(support_dir))
    
    for label_idx, class_name in enumerate(class_names):
        class_dir = os.path.join(support_dir, class_name)
        if not os.path.isdir(class_dir): continue
            
        # Take K images per class to build prototypes
        images = os.listdir(class_dir)[:model.hparams.k_shot]
        for img_name in images:
            img = Image.open(os.path.join(class_dir, img_name)).convert('RGB')
            support_images.append(transform(img))
            support_labels.append(label_idx)
            
    support_tensor = torch.stack(support_images).to(device) # [N*K, C, H, W]
    
    # 3. Load Query Image
    q_img = Image.open(query_image_path).convert('RGB')
    query_tensor = transform(q_img).unsqueeze(0).to(device) # [1, C, H, W]
    
    # 4. Inference
    with torch.no_grad():
        # Get embeddings
        support_emb = model(support_tensor) # [N*K, Dim]
        query_emb = model(query_tensor)     # [1, Dim]
        
        # Compute Prototypes: average embeddings per class
        # Dimension: [N, Dim]
        prototypes = torch.stack([
            support_emb[torch.tensor(support_labels) == c].mean(dim=0) 
            for c in range(len(class_names))
        ])
        
        # Compute distance: $d(Q, P)$
        distances = torch.cdist(query_emb, prototypes) # [1, N]
        
        # Prediction is the index of the minimum distance
        pred_idx = torch.argmin(distances, dim=1).item()
        
    print(f"Predicted Class: {class_names[pred_idx]}")
    return class_names[pred_idx]

if __name__ == '__main__':
    # Update with actual checkpoint name generated by Script 1
    CHECKPOINT = "./resources/checkpoints/protonet-epoch=09.ckpt"
    
    # Path containing subfolders of new classes (e.g., K images per folder)
    SUPPORT_DIR = "./datasets/meta_learning/test" 
    
    # The new image you want to classify
    QUERY_IMAGE = "./datasets/meta_learning/test/glass/glass10.jpg"
    
    predict_single_image(CHECKPOINT, SUPPORT_DIR, QUERY_IMAGE)
